"""Build a packed 640x480 flash background using the application's geometry.

Matches fillCircle and size-1 GLCD text in VGA/vga16_graphics_v3.c.
Run by CMake; no flash writes or third RAM framebuffer are needed at runtime.
"""
import argparse
import math
from pathlib import Path
import re
import struct


def generate(source, font_source):
    def constant(name):
        match = re.search(r'^#define\s+' + name + r'\s+(\d+)\b', source, re.M)
        if not match:
            raise ValueError(f'{name} must be an integer literal for background generation')
        return int(match[1])

    font_body = font_source.split('font[] = {', 1)[1].split('}', 1)[0]
    font_body = re.sub(r'//[^\n]*|/\*.*?\*/', '', font_body, flags=re.S)
    font = bytes(int(v, 16) for v in re.findall(r'0x[0-9a-fA-F]+', font_body))
    frame = bytearray(640 * 480 // 8)

    def pixel(x, y, color):
        if 0 <= x < 640 and 0 <= y < 480:
            index, shift = (640 * y + x) >> 3, x & 7
            frame[index] = (frame[index] & ~(1 << shift)) | (int(color != 0) << shift)

    radius = constant('PEG_RADIUS')
    for row in range(constant('PEG_ROWS')):
        left = constant('FIRST_PEG_X') - row * constant('PEG_HORIZONTAL_SPACING') // 2
        y = constant('FIRST_PEG_Y') + row * constant('PEG_VERTICAL_SPACING')
        for column in range(row + 1):
            x = left + column * constant('PEG_HORIZONTAL_SPACING')
            for offset in range(radius + 1):
                half = math.isqrt(radius * radius + radius - offset * offset)
                for px in range(x - half, x + half):
                    pixel(px, y + offset, 12)  # MAGENTA
                    pixel(px, y - offset, 12)

    labels = ('# of balls animated: ', '# of balls fallen: ',
              'bounciness: ', 'time since boot: ')
    for index, label in enumerate(labels):
        for char_index, char in enumerate(label):
            for column in range(6):
                bits = font[ord(char) * 5 + column] if column < 5 else 0
                for bit in range(8):
                    pixel(10 + char_index * 6 + column, 20 + index * 10 + bit,
                          15 if bits & (1 << bit) else 0)
    return frame, labels


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('font', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    font_source = args.font.read_text()
    frame, labels = generate(args.source.read_text(), font_source)
    # Retain the font's license in the generated derivative.
    license_text = font_source[:font_source.index('*/') + 2]
    lines = [license_text, '// Generated by generate_galton_background.py. Do not edit.',
             '#pragma once', '#include <stdint.h>',
             'static const short background_value_x[4] = {' +
             ', '.join(str(10 + 6 * len(label)) for label in labels) + '};',
             'static const uint32_t galton_background[9600] = {']
    words = struct.unpack('<9600I', frame)
    for start in range(0, len(words), 8):
        lines.append('    ' + ', '.join(f'0x{v:08x}u' for v in words[start:start + 8]) + ',')
    lines.append('};')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
